"""Create PLM-IQ database schema SQL from the YAML profiles in profiles/.

Compiles each profile (resolving its inheritance chain) into
generated/<profile_id>/db/schema.sql (PostgreSQL DDL + seed data) and
generated/<profile_id>/db/profile-ir.json (resolved profile IR).

Two-step workflow (generate, verify, then deploy exactly what you reviewed):

    python database/scripts/create_db.py                       # 1. write schema.sql files
    python database/scripts/create_db.py --apply               # 2a. deploy freshly generated SQL
    python database/scripts/create_db.py --schema-file PATH... # 2b. deploy previously generated files

One-step workflow (generate + apply in a single pass):

    python database/scripts/create_db.py --apply --drop
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from engine.compiler.profile import ProfileError, ResolvedProfile, resolve_profile  # noqa: E402
from generators.database.sql_generator import generate_schema_sql  # noqa: E402

PROFILES_DIR = REPO_ROOT / "profiles"
GENERATED_DIR = REPO_ROOT / "generated"
DEFAULT_DATABASE_URL = "postgresql://plmiq:plmiq@localhost:5432/plmiq"


def available_profile_files() -> list[Path]:
    return sorted({*PROFILES_DIR.glob("*.yaml"), *PROFILES_DIR.glob("*.yml")})


def select_profiles(requested: list[str] | None) -> list[Path]:
    files = available_profile_files()
    if not requested:
        return files
    selected: list[Path] = []
    for wanted in requested:
        matches = [path for path in files if path.stem == wanted or path.name == wanted]
        if not matches:
            available = ", ".join(path.stem for path in files)
            raise SystemExit(f"error: profile not found '{wanted}' (available: {available})")
        selected.extend(matches)
    return selected


def write_artifacts(profile: ResolvedProfile) -> tuple[Path, Path]:
    out_dir = GENERATED_DIR / profile.profile_id / "db"
    out_dir.mkdir(parents=True, exist_ok=True)
    schema_path = out_dir / "schema.sql"
    ir_path = out_dir / "profile-ir.json"
    schema_path.write_text(generate_schema_sql(profile), encoding="utf-8", newline="\n")
    ir_path.write_text(json.dumps(profile.to_dict(), indent=2, default=str) + "\n", encoding="utf-8", newline="\n")
    return schema_path, ir_path


def apply_schemas(database_url: str, schemas: list[str], drop: bool) -> None:
    try:
        import psycopg2
    except ImportError as exc:  # pragma: no cover - environment guard
        raise SystemExit("error: psycopg2 is required for --apply (pip install psycopg2-binary)") from exc

    connection = psycopg2.connect(database_url)
    try:
        with connection.cursor() as cursor:
            if drop:
                print("dropping schema public")
                cursor.execute("DROP SCHEMA IF EXISTS public CASCADE")
                cursor.execute("CREATE SCHEMA public")
            for index, schema_sql in enumerate(schemas, start=1):
                cursor.execute(schema_sql)
                print(f"applied schema {index}/{len(schemas)}")
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def load_schema_files(paths: list[str]) -> list[str]:
    schemas: list[str] = []
    for raw_path in paths:
        path = Path(raw_path)
        if not path.is_file():
            raise SystemExit(f"error: schema file not found: {path} (generate it first with no --schema-file)")
        schema = path.read_text(encoding="utf-8")
        if not schema.lstrip().startswith("-- AUTO-GENERATED BY PLM-IQ"):
            print(f"warning: {path} does not look like a generated PLM-IQ schema", file=sys.stderr)
        schemas.append(schema)
        print(f"loaded {path} ({len(schema.splitlines())} lines)")
    return schemas


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate PLM-IQ database schema from YAML profiles.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--profile",
        action="append",
        dest="profiles",
        help="profile id or YAML file name (repeatable); default: all profiles",
    )
    parser.add_argument("--stdout", action="store_true", help="print SQL to stdout instead of writing files")
    parser.add_argument("--apply", action="store_true", help="also apply the generated schema to PostgreSQL")
    parser.add_argument(
        "--schema-file",
        action="append",
        dest="schema_files",
        metavar="PATH",
        help="deploy an existing generated schema.sql file instead of regenerating "
        "(repeatable; implies deployment, use after reviewing the SQL)",
    )
    parser.add_argument("--drop", action="store_true", help="drop the public schema before deploying")
    parser.add_argument(
        "--database-url",
        default=os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL),
        help="PostgreSQL URL for --apply (default: $DATABASE_URL or %(default)s)",
    )
    args = parser.parse_args(argv)

    if args.schema_files and (args.profiles or args.stdout):
        parser.error("--schema-file deploys existing files and cannot be combined with --profile or --stdout")

    schemas: list[str] = []
    if args.schema_files:
        schemas = load_schema_files(args.schema_files)
    else:
        resolved: list[ResolvedProfile] = []
        for path in select_profiles(args.profiles):
            try:
                profile = resolve_profile(path)
            except ProfileError as exc:
                raise SystemExit(f"error: {exc}") from exc
            resolved.append(profile)

        for profile in resolved:
            sql = generate_schema_sql(profile)
            schemas.append(sql)
            if args.stdout:
                print(sql)
            else:
                schema_path, ir_path = write_artifacts(profile)
                print(f"generated {schema_path.relative_to(REPO_ROOT).as_posix()} ({len(sql.splitlines())} lines)")
                print(f"generated {ir_path.relative_to(REPO_ROOT).as_posix()}")

    if args.apply or args.schema_files:
        apply_schemas(args.database_url, schemas, drop=args.drop)
        print(f"done: {len(schemas)} schema(s) applied to {args.database_url}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
