"""Unit tests for the SQL schema generator."""

import re
from pathlib import Path

import pytest

from engine.compiler.profile import resolve_profile
from generators.database.sql_generator import generate_schema_sql

PROFILES_DIR = Path(__file__).resolve().parents[2] / "profiles"

EXPECTED_TABLES = (
    "profile",
    "tenant",
    "app_user",
    "role",
    "vertex_type",
    "attribute_definition",
    "edge_type",
    "edge_attribute_definition",
    "vertex",
    "vertex_attribute",
    "edge",
    "edge_annotation",
    "vertex_revision",
    "lifecycle",
    "lifecycle_state",
    "lifecycle_transition",
    "graph_query",
    "workflow_definition",
    "workflow_stage",
    "workflow_instance",
    "workflow_task",
    "profile_section",
    "audit_log",
)


@pytest.fixture(scope="module")
def sql():
    return generate_schema_sql(resolve_profile(PROFILES_DIR / "discrete-extended.yaml"))


def test_all_core_tables_present(sql):
    for table in EXPECTED_TABLES:
        assert f"CREATE TABLE IF NOT EXISTS {table} (" in sql, f"missing table '{table}'"


def test_generated_header(sql):
    assert sql.startswith("-- AUTO-GENERATED BY PLM-IQ")
    assert "DO NOT EDIT" in sql
    assert "discrete-extended" in sql


def test_seed_uuids_are_deterministic(sql):
    assert "md5('discrete-extended|vertex_type|part')::uuid" in sql
    assert "md5('discrete-plm|vertex_type|part')::uuid" not in sql


def test_seeds_cover_resolved_meta_model(sql):
    # inherited from plm-core
    assert "'document'" in sql and "'DOCUMENTED_BY'" in sql
    # added by discrete profiles
    assert "'has_component'" in sql
    assert "'HAS_COMPONENT'" in sql
    # lifecycle seeded with states and transitions
    assert "'IN_REVIEW'" in sql
    assert "'submit'" in sql
    # workflows and graph queries
    assert "'part_release'" in sql
    assert "'engineering_change_order'" in sql
    assert "'complete_engineering_impact'" in sql
    # config sections captured as JSONB
    assert "'search'" in sql
    assert "'ai'" in sql
    assert "'ui'" in sql


def test_edge_annotations_seeded(sql):
    assert "'quantity'" in sql
    assert "'find_number'" in sql
    assert "'lead_time_days'" in sql


def test_no_python_none_leaks_into_sql(sql):
    match = re.search(r"\bNone\b", sql)
    assert match is None, f"raw None leaked into SQL at offset {match.start()}" if match else ""


def test_every_insert_is_idempotent(sql):
    inserts = re.findall(r"INSERT INTO (\w+)[^;]+?ON CONFLICT", sql, flags=re.DOTALL)
    assert inserts, "expected upsert-style seed statements"
    assert len(inserts) == len(re.findall(r"INSERT INTO", sql)), "every INSERT must have ON CONFLICT"


def test_plm_core_sql_is_self_contained():
    sql = generate_schema_sql(resolve_profile(PROFILES_DIR / "plm-core.yaml"))
    assert "md5('plm-core|vertex_type|vertex')::uuid" in sql
    assert "'related_to'" in sql
    code_only = re.sub(r"--[^\n]*", "", sql)
    assert "'part'" not in code_only, "plm-core schema must not contain discrete-only metadata"
