-- ============================================================
-- PLM-IQ — Seed Data
-- Generated: 2026-06-25T14:21:05.168546
-- ============================================================

PRAGMA foreign_keys = OFF;

-- tenants (5 dummy tenants)
INSERT INTO tenants (tenant_id, tenant_name, description, created_date, is_active) VALUES
    (1, 'BicycleCo', 'Primary bicycle manufacturing company', '2020-01-01', TRUE),
    (2, 'CycleWorks', 'High-end bicycle components manufacturer', '2020-06-15', TRUE),
    (3, 'VeloParts', 'Aftermarket parts distributor', '2021-03-01', TRUE),
    (4, 'BikeTech Industries', 'Electric bicycle systems and components', '2022-01-10', TRUE),
    (5, 'PedalForce', 'Custom bicycle frames and carbon fiber components', '2021-09-20', TRUE);

-- users (5 users, all belonging to BicycleCo tenant_id=1)
-- Default password for all users: user1234 (bcrypt hash)
INSERT OR IGNORE INTO users (user_id, username, full_name, email, password_hash, tenant_id, is_active, created_date) VALUES
    (1, 'megan', 'Megan Foster', 'megan.foster@bicycleco.com', '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, TRUE, '2020-01-01'),
    (2, 'jane', 'Jane Chen', 'jane.chen@bicycleco.com', '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, TRUE, '2020-01-01'),
    (3, 'nik', 'Nik Patel', 'nik.patel@bicycleco.com', '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, TRUE, '2020-06-01'),
    (4, 'mike', 'Mike Torres', 'mike.torres@bicycleco.com', '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, TRUE, '2021-02-15'),
    (5, 'john', 'John Kim', 'john.kim@bicycleco.com', '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, TRUE, '2021-08-01');

-- parts (141 rows from bicycle-parts.csv)
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'volume\\Complete Bicycle - 21-Speed Hybrid', 'Aluminum frame hybrid bike', 'EA', 1, 'DRAFT', '22-03-2013', '11-08-2013', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-001', 'J', 'Frame Assembly', 'volume\\Frame Assembly', 'TIG-welded aluminum 6061', 'EA', 1, 'DRAFT', '03-01-2014', '18-08-2024', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-002', 'A', 'Frame - Main Triangle', 'volume\\Frame - Main Triangle', 'Double-butted aluminum', 'EA', 1, 'DRAFT', '03-02-2014', '26-11-2016', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-003', 'F', 'Top Tube', 'volume\\Top Tube', 'Aluminum 6061-T6 - 560mm', 'EA', 1, 'RELEASED', '31-05-2021', '24-12-2022', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-004', 'O', 'Down Tube', 'volume\\Down Tube', 'Aluminum 6061-T6 - tapered', 'EA', 1, 'RELEASED', '21-10-2010', '19-01-2021', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-005', 'Y', 'Seat Tube', 'volume\\Seat Tube', 'Aluminum 6061-T6 - 480mm', 'EA', 1, 'RELEASED', '04-05-2025', '20-05-2026', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-006', 'I', 'Head Tube', 'volume\\Head Tube', 'Aluminum 6061-T6 - 110mm', 'EA', 1, 'OBSOLETED', '22-04-2020', '07-06-2020', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-007', 'C', 'Chain Stays (Pair)', 'volume\\Chain Stays (Pair)', 'Aluminum 6061-T6 - 425mm', 'PR', 1, 'DRAFT', '19-04-2022', '11-09-2025', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-008', 'F', 'Seat Stays (Pair)', 'volume\\Seat Stays (Pair)', 'Aluminum 6061-T6 - 380mm', 'PR', 1, 'OBSOLETED', '13-11-2022', '07-09-2023', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-009', 'V', 'Bottom Bracket Shell', 'volume\\Bottom Bracket Shell', 'Threaded BSA 68mm', 'EA', 1, 'DRAFT', '12-09-2025', '03-11-2025', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-010', 'M', 'Dropouts - Rear', 'volume\\Dropouts - Rear', 'Steel forged - 135mm OLD', 'EA', 2, 'RELEASED', '09-09-2014', '29-01-2023', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-011', 'B', 'Cable Guides', 'volume\\Cable Guides', 'Plastic', 'EA', 4, 'RELEASED', '04-09-2013', '31-05-2021', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-012', 'X', 'Derailleur Hanger', 'volume\\Derailleur Hanger', 'Aluminum replaceable', 'EA', 1, 'DRAFT', '28-09-2017', '08-03-2025', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-013', 'D', 'Frame Decals', 'volume\\Frame Decals', 'Vinyl', 'ST', 1, 'DRAFT', '12-06-2015', '04-01-2024', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FRM-014', 'F', 'Frame Paint/Powdercoat', 'volume\\Frame Paint/Powdercoat', 'Powdercoat matte black', 'EA', 1, 'RELEASED', '16-06-2015', '03-05-2017', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FORK-001', 'O', 'Fork Assembly', 'volume\\Fork Assembly', 'Rigid steel fork', 'EA', 1, 'DRAFT', '18-05-2015', '24-02-2024', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FORK-002', 'M', 'Fork Legs (Pair)', 'volume\\Fork Legs (Pair)', 'Chrome-moly steel', 'PR', 1, 'OBSOLETED', '04-08-2022', '10-09-2023', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FORK-003', 'R', 'Steerer Tube', 'volume\\Steerer Tube', 'Chrome-moly steel - 1-1/8"', 'EA', 1, 'RELEASED', '09-04-2016', '10-11-2023', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FORK-004', 'L', 'Fork Crown', 'volume\\Fork Crown', 'Steel investment cast', 'EA', 1, 'DRAFT', '07-12-2012', '12-04-2013', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FORK-005', 'F', 'Fork Dropouts', 'volume\\Fork Dropouts', 'Steel - 100mm OLD', 'EA', 2, 'RELEASED', '06-02-2016', '17-02-2025', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('FORK-006', 'G', 'Brake Mount (Cantilever Posts)', 'volume\\Brake Mount (Cantilever Posts)', 'Steel brazed-on', 'EA', 2, 'DRAFT', '14-10-2018', '07-08-2020', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-001', 'H', 'Drivetrain Assembly', 'volume\\Drivetrain Assembly', '21-speed drivetrain', 'EA', 1, 'OBSOLETED', '18-08-2013', '04-08-2022', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-002', 'P', 'Crankset Assembly', 'volume\\Crankset Assembly', 'Shimano FC-TY301 42/34/24T', 'EA', 1, 'DRAFT', '18-07-2016', '04-08-2022', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CRK-001', 'F', 'Right Crank Arm (w/ chainrings)', 'volume\\Right Crank Arm (w/ chainrings)', 'Aluminum forged - 170mm', 'EA', 1, 'DRAFT', '16-04-2016', '29-10-2025', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CRK-002', 'H', 'Left Crank Arm', 'volume\\Left Crank Arm', 'Aluminum forged - 170mm', 'EA', 1, 'DRAFT', '13-10-2013', '12-06-2016', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CRK-003', 'S', 'Inner Chainring 24T', 'volume\\Inner Chainring 24T', 'Steel', 'EA', 1, 'OBSOLETED', '03-10-2023', '20-10-2025', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CRK-004', 'A', 'Middle Chainring 34T', 'volume\\Middle Chainring 34T', 'Steel', 'EA', 1, 'OBSOLETED', '08-01-2013', '16-10-2013', 2);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CRK-005', 'U', 'Outer Chainring 42T', 'volume\\Outer Chainring 42T', 'Steel', 'EA', 1, 'OBSOLETED', '29-12-2025', '24-05-2026', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CRK-006', 'T', 'Chainring Bolts', 'volume\\Chainring Bolts', 'Steel M8', 'EA', 5, 'DRAFT', '07-07-2022', '21-11-2024', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-003', 'O', 'Bottom Bracket', 'volume\\Bottom Bracket', 'Shimano BB-UN300 - 68x110mm', 'EA', 1, 'OBSOLETED', '06-08-2016', '28-07-2017', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BB-001', 'J', 'Bottom Bracket Cup LH', 'volume\\Bottom Bracket Cup LH', 'Steel - left thread', 'EA', 1, 'OBSOLETED', '05-09-2015', '29-09-2024', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BB-002', 'N', 'Bottom Bracket Cup RH', 'volume\\Bottom Bracket Cup RH', 'Steel - right thread', 'EA', 1, 'OBSOLETED', '01-11-2022', '16-09-2025', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BB-003', 'N', 'Bottom Bracket Spindle', 'volume\\Bottom Bracket Spindle', 'Chrome-moly steel', 'EA', 1, 'DRAFT', '06-04-2019', '25-07-2023', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BB-004', 'Q', 'Bearing Retainer (LH)', 'volume\\Bearing Retainer (LH)', 'Steel w/ ball bearings', 'EA', 1, 'DRAFT', '04-12-2014', '11-06-2024', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BB-005', 'U', 'Bearing Retainer (RH)', 'volume\\Bearing Retainer (RH)', 'Steel w/ ball bearings', 'EA', 1, 'RELEASED', '14-04-2024', '30-09-2024', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('BB-006', 'U', 'Lock Ring', 'volume\\Lock Ring', 'Steel', 'EA', 1, 'DRAFT', '10-03-2013', '23-10-2014', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-004', 'T', 'Rear Cassette', 'volume\\Rear Cassette', 'Shimano MF-TZ21 14-34T 7-speed', 'EA', 1, 'RELEASED', '22-10-2016', '13-03-2021', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-001', 'X', 'Cog 14T', 'volume\\Cog 14T', 'Nickel-plated steel', 'EA', 1, 'OBSOLETED', '02-07-2017', '18-07-2017', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-002', 'M', 'Cog 16T', 'volume\\Cog 16T', 'Nickel-plated steel', 'EA', 1, 'DRAFT', '25-01-2011', '14-04-2026', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-003', 'F', 'Cog 18T', 'volume\\Cog 18T', 'Nickel-plated steel', 'EA', 1, 'RELEASED', '04-03-2019', '16-07-2023', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-004', 'E', 'Cog 21T', 'volume\\Cog 21T', 'Nickel-plated steel', 'EA', 1, 'DRAFT', '26-08-2024', '24-11-2025', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-005', 'Y', 'Cog 24T', 'volume\\Cog 24T', 'Nickel-plated steel', 'EA', 1, 'OBSOLETED', '07-06-2011', '13-10-2013', 5);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-006', 'B', 'Cog 28T', 'volume\\Cog 28T', 'Nickel-plated steel', 'EA', 1, 'DRAFT', '19-05-2011', '13-04-2019', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CST-007', 'F', 'Cog 34T', 'volume\\Cog 34T', 'Nickel-plated steel', 'EA', 1, 'DRAFT', '23-01-2017', '10-12-2024', 3);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-005', 'J', 'Front Derailleur', 'volume\\Front Derailleur', 'Shimano FD-TY700 top-swing', 'EA', 1, 'RELEASED', '15-09-2014', '08-09-2025', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-006', 'C', 'Rear Derailleur', 'volume\\Rear Derailleur', 'Shimano RD-TY300', 'EA', 1, 'OBSOLETED', '30-08-2017', '17-03-2025', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-007', 'G', 'Shifters (Pair)', 'volume\\Shifters (Pair)', 'Shimano ST-EF41 7-speed trigger', 'ST', 1, 'OBSOLETED', '16-06-2025', '11-02-2026', 4);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('DRV-008', 'C', 'Shift Cables (Pair)', 'volume\\Shift Cables (Pair)', 'Galvanized 1.2mm w/ housing', 'ST', 1, 'DRAFT', '16-02-2026', '06-04-2026', 1);
INSERT INTO parts (part_number, part_revision, part_name, spec_file, material, uom, qty, status, created_date, modified_date, modified_owner) VALUES ('CBL-001', 'K', 'Shift Inner Cable (Rear)', 'volume\\Shift Inner Cable (Rear)', 'Galvanized steel 1.2mm', 'EA', 1, 'DRAFT', '15-04-2016', '14-01-2025', 2);
-- bom (141 rows from bicycle-bom.csv)
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (0, 'BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 1, 'EA', NULL, NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'FRM-001', 'J', 'Frame Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-002', 'A', 'Frame - Main Triangle', 1, 'EA', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'FRM-003', 'F', 'Top Tube', 1, 'EA', 'FRM-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'FRM-004', 'O', 'Down Tube', 1, 'EA', 'FRM-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'FRM-005', 'Y', 'Seat Tube', 1, 'EA', 'FRM-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'FRM-006', 'I', 'Head Tube', 1, 'EA', 'FRM-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'FRM-007', 'C', 'Chain Stays (Pair)', 1, 'PR', 'FRM-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'FRM-008', 'F', 'Seat Stays (Pair)', 1, 'PR', 'FRM-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-009', 'V', 'Bottom Bracket Shell', 1, 'EA', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-010', 'M', 'Dropouts - Rear', 2, 'EA', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-011', 'B', 'Cable Guides', 4, 'EA', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-012', 'X', 'Derailleur Hanger', 1, 'EA', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-013', 'D', 'Frame Decals', 1, 'ST', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FRM-014', 'F', 'Frame Paint/Powdercoat', 1, 'EA', 'FRM-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'FORK-001', 'O', 'Fork Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FORK-002', 'M', 'Fork Legs (Pair)', 1, 'PR', 'FORK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FORK-003', 'R', 'Steerer Tube', 1, 'EA', 'FORK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FORK-004', 'L', 'Fork Crown', 1, 'EA', 'FORK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FORK-005', 'F', 'Fork Dropouts', 2, 'EA', 'FORK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'FORK-006', 'G', 'Brake Mount (Cantilever Posts)', 2, 'EA', 'FORK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'DRV-001', 'H', 'Drivetrain Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-002', 'P', 'Crankset Assembly', 1, 'EA', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CRK-001', 'F', 'Right Crank Arm (w/ chainrings)', 1, 'EA', 'DRV-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CRK-002', 'H', 'Left Crank Arm', 1, 'EA', 'DRV-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CRK-003', 'S', 'Inner Chainring 24T', 1, 'EA', 'DRV-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CRK-004', 'A', 'Middle Chainring 34T', 1, 'EA', 'DRV-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CRK-005', 'U', 'Outer Chainring 42T', 1, 'EA', 'DRV-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CRK-006', 'T', 'Chainring Bolts', 5, 'EA', 'DRV-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-003', 'O', 'Bottom Bracket', 1, 'EA', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'BB-001', 'J', 'Bottom Bracket Cup LH', 1, 'EA', 'DRV-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'BB-002', 'N', 'Bottom Bracket Cup RH', 1, 'EA', 'DRV-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'BB-003', 'N', 'Bottom Bracket Spindle', 1, 'EA', 'DRV-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'BB-004', 'Q', 'Bearing Retainer (LH)', 1, 'EA', 'DRV-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'BB-005', 'U', 'Bearing Retainer (RH)', 1, 'EA', 'DRV-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'BB-006', 'U', 'Lock Ring', 1, 'EA', 'DRV-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-004', 'T', 'Rear Cassette', 1, 'EA', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-001', 'X', 'Cog 14T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-002', 'M', 'Cog 16T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-003', 'F', 'Cog 18T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-004', 'E', 'Cog 21T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-005', 'Y', 'Cog 24T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-006', 'B', 'Cog 28T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CST-007', 'F', 'Cog 34T', 1, 'EA', 'DRV-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-005', 'J', 'Front Derailleur', 1, 'EA', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-006', 'C', 'Rear Derailleur', 1, 'EA', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-007', 'G', 'Shifters (Pair)', 1, 'ST', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-008', 'C', 'Shift Cables (Pair)', 1, 'ST', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-001', 'K', 'Shift Inner Cable (Rear)', 1, 'EA', 'DRV-008', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-002', 'B', 'Shift Inner Cable (Front)', 1, 'EA', 'DRV-008', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-003', 'O', 'Shift Cable Housing', 2, 'EA', 'DRV-008', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-004', 'T', 'Cable End Caps', 4, 'EA', 'DRV-008', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-005', 'Q', 'Cable Ferrules', 4, 'EA', 'DRV-008', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'DRV-009', 'H', 'Chain', 1, 'EA', 'DRV-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'WHL-001', 'J', 'Front Wheel Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-002', 'W', 'Rim - Front', 1, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-003', 'Z', 'Front Hub', 1, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-001', 'P', 'Hub Shell - Front', 1, 'EA', 'WHL-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-002', 'T', 'Hub Axle - Front', 1, 'EA', 'WHL-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-003', 'Q', 'Ball Bearings - Front Hub', 2, 'ST', 'WHL-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-004', 'P', 'Hub Cones - Front', 2, 'EA', 'WHL-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-005', 'O', 'Hub Locknuts - Front', 2, 'EA', 'WHL-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-006', 'E', 'Quick Release Skewer - Front', 1, 'EA', 'WHL-003', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-004', 'L', 'Spokes - Front', 32, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-005', 'E', 'Spoke Nipples - Front', 32, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-006', 'I', 'Rim Tape - Front', 1, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-007', 'L', 'Inner Tube - Front', 1, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-008', 'E', 'Tire - Front', 1, 'EA', 'WHL-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'WHL-009', 'U', 'Rear Wheel Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-010', 'O', 'Rim - Rear', 1, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-011', 'K', 'Rear Hub', 1, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-007', 'B', 'Hub Shell - Rear', 1, 'EA', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-008', 'U', 'Hub Axle - Rear', 1, 'EA', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-009', 'P', 'Ball Bearings - Rear Hub', 2, 'ST', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-010', 'P', 'Hub Cones - Rear', 2, 'EA', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-011', 'Q', 'Hub Locknuts - Rear', 2, 'EA', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-012', 'X', 'Freewheel Body', 1, 'EA', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HUB-013', 'M', 'Quick Release Skewer - Rear', 1, 'EA', 'WHL-011', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-012', 'U', 'Spokes - Rear', 32, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-013', 'R', 'Spoke Nipples - Rear', 32, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-014', 'C', 'Rim Tape - Rear', 1, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-015', 'Q', 'Inner Tube - Rear', 1, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'WHL-016', 'A', 'Tire - Rear', 1, 'EA', 'WHL-009', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'BRK-001', 'Y', 'Braking System Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'BRK-002', 'V', 'Brake Lever (Left)', 1, 'EA', 'BRK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'BRK-003', 'C', 'Brake Lever (Right)', 1, 'EA', 'BRK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'BRK-004', 'B', 'Front Brake Caliper', 1, 'EA', 'BRK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-001', 'N', 'Brake Arm LH - Front', 1, 'EA', 'BRK-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-002', 'A', 'Brake Arm RH - Front', 1, 'EA', 'BRK-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-003', 'P', 'Brake Spring - Front', 2, 'EA', 'BRK-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-004', 'M', 'Brake Pivot Bolts - Front', 2, 'EA', 'BRK-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-005', 'H', 'Quick-Release Cable Mechanism', 1, 'EA', 'BRK-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-006', 'D', 'Brake Pad Set - Front', 2, 'EA', 'BRK-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'BRK-005', 'A', 'Rear Brake Caliper', 1, 'EA', 'BRK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-007', 'D', 'Brake Arm LH - Rear', 1, 'EA', 'BRK-005', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-008', 'A', 'Brake Arm RH - Rear', 1, 'EA', 'BRK-005', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-009', 'Q', 'Brake Spring - Rear', 2, 'EA', 'BRK-005', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-010', 'J', 'Brake Pivot Bolts - Rear', 2, 'EA', 'BRK-005', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CLP-011', 'N', 'Brake Pad Set - Rear', 2, 'EA', 'BRK-005', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'BRK-006', 'A', 'Brake Cables (Pair)', 1, 'ST', 'BRK-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-006', 'Z', 'Brake Inner Cable (Front)', 1, 'EA', 'BRK-006', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-007', 'H', 'Brake Inner Cable (Rear)', 1, 'EA', 'BRK-006', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-008', 'T', 'Brake Cable Housing', 2, 'EA', 'BRK-006', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'CBL-009', 'D', 'Brake Cable End Caps', 4, 'EA', 'BRK-006', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'CPT-001', 'N', 'Cockpit Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'CPT-002', 'Q', 'Handlebar', 1, 'EA', 'CPT-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'CPT-003', 'L', 'Stem', 1, 'EA', 'CPT-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'CPT-004', 'M', 'Headset', 1, 'EA', 'CPT-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HDS-001', 'D', 'Headset Top Cap', 1, 'EA', 'CPT-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HDS-002', 'X', 'Headset Compression Ring', 1, 'EA', 'CPT-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HDS-003', 'K', 'Upper Bearing', 1, 'EA', 'CPT-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HDS-004', 'U', 'Lower Bearing', 1, 'EA', 'CPT-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HDS-005', 'C', 'Headset Crown Race', 1, 'EA', 'CPT-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'HDS-006', 'C', 'Star Nut', 1, 'EA', 'CPT-004', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'CPT-005', 'D', 'Grips (Pair)', 1, 'PR', 'CPT-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'CPT-006', 'W', 'Handlebar Stem Bolts', 4, 'EA', 'CPT-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'CPT-007', 'J', 'Headset Top Cap Bolt', 1, 'EA', 'CPT-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'SET-001', 'Y', 'Seat Assembly', 1, 'EA', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'SET-002', 'Y', 'Saddle', 1, 'EA', 'SET-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'SDL-001', 'K', 'Saddle Shell', 1, 'EA', 'SET-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'SDL-002', 'D', 'Saddle Padding', 1, 'EA', 'SET-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'SDL-003', 'N', 'Saddle Cover', 1, 'EA', 'SET-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (3, 'SDL-004', 'H', 'Saddle Rails (Pair)', 1, 'PR', 'SET-002', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'SET-003', 'Z', 'Seatpost', 1, 'EA', 'SET-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'SET-004', 'M', 'Seatpost Clamp', 1, 'EA', 'SET-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'SET-005', 'O', 'Seatpost Clamp Bolt', 1, 'EA', 'SET-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'SET-006', 'L', 'Saddle Clamp Bolts', 2, 'EA', 'SET-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'PED-001', 'Y', 'Pedals (Pair)', 1, 'PR', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'PED-002', 'U', 'Pedal Body (Left)', 1, 'EA', 'PED-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'PED-003', 'Y', 'Pedal Body (Right)', 1, 'EA', 'PED-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'PED-004', 'E', 'Pedal Spindle (Left)', 1, 'EA', 'PED-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'PED-005', 'C', 'Pedal Spindle (Right)', 1, 'EA', 'PED-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'PED-006', 'V', 'Pedal Bearings', 4, 'EA', 'PED-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'PED-007', 'Q', 'Pedal Reflectors', 2, 'EA', 'PED-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (1, 'HDW-001', 'Q', 'Hardware & Fasteners Kit', 1, 'ST', 'BIKE-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'HDW-002', 'P', 'Water Bottle Bolts', 4, 'EA', 'HDW-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'HDW-003', 'L', 'Water Bottle Cage', 2, 'EA', 'HDW-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'HDW-004', 'P', 'Chainstay Protector', 1, 'EA', 'HDW-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'HDW-005', 'O', 'Reflector Kit', 1, 'ST', 'HDW-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'HDW-006', 'M', 'Kickstand', 1, 'EA', 'HDW-001', NULL, 'DESIGN');
INSERT INTO bom (level, part_number, part_revision, part_name, qty, uom, parent_assembly, material_notes, bom_type) VALUES (2, 'HDW-007', 'T', 'Kickstand Bolt', 1, 'EA', 'HDW-001', NULL, 'DESIGN');

-- costing_bom (141 rows from costing-bom.csv)
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (0, 'BIKE-001', 'Complete Bicycle - 21-Speed Hybrid', 1, 'EA', 0.00, 15.00, 3.75, 0.00, 18.7500, 439.68, 439.68, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (1, 'FRM-001', 'Frame Assembly', 1, 'EA', 0.00, 8.00, 2.00, 0.00, 10.0000, 74.55, 74.55, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-002', 'Frame - Main Triangle', 1, 'EA', 0.00, 5.00, 1.25, 0.00, 6.2500, 46.34, 46.34, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'FRM-003', 'Top Tube', 1, 'EA', 2.50, 3.00, 0.75, 1.50, 7.7500, 7.75, 7.75, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'FRM-004', 'Down Tube', 1, 'EA', 3.20, 3.50, 0.88, 2.00, 9.5800, 9.58, 9.58, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'FRM-005', 'Seat Tube', 1, 'EA', 2.00, 2.50, 0.63, 1.20, 6.3300, 6.33, 6.33, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'FRM-006', 'Head Tube', 1, 'EA', 1.50, 2.00, 0.50, 1.00, 5.0000, 5.00, 5.00, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'FRM-007', 'Chain Stays (Pair)', 1, 'PR', 1.80, 2.50, 0.63, 1.50, 6.4300, 6.43, 6.43, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'FRM-008', 'Seat Stays (Pair)', 1, 'PR', 1.50, 2.00, 0.50, 1.00, 5.0000, 5.00, 5.00, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-009', 'Bottom Bracket Shell', 1, 'EA', 1.20, 0.80, 0.20, 1.50, 3.7000, 3.70, 3.70, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-010', 'Dropouts - Rear', 2, 'EA', 0.60, 1.20, 0.30, 0.80, 2.9000, 5.80, 2.90, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-011', 'Cable Guides', 4, 'EA', 0.15, 0.05, 0.01, 0.00, 0.2100, 0.84, 0.21, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-012', 'Derailleur Hanger', 1, 'EA', 0.40, 0.50, 0.13, 0.60, 1.6300, 1.63, 1.63, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-013', 'Frame Decals', 1, 'ST', 0.30, 0.15, 0.04, 0.00, 0.4900, 0.49, 0.49, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FRM-014', 'Frame Paint/Powdercoat', 1, 'EA', 2.00, 3.00, 0.75, 0.00, 5.7500, 5.75, 5.75, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (1, 'FORK-001', 'Fork Assembly', 1, 'EA', 0.00, 5.00, 1.25, 0.00, 6.2500, 36.14, 36.14, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FORK-002', 'Fork Legs (Pair)', 1, 'PR', 3.50, 4.00, 1.00, 2.00, 10.5000, 10.50, 10.50, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FORK-003', 'Steerer Tube', 1, 'EA', 2.00, 2.50, 0.63, 1.50, 6.6300, 6.63, 6.63, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FORK-004', 'Fork Crown', 1, 'EA', 2.50, 2.00, 0.50, 1.50, 6.5000, 6.50, 6.50, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FORK-005', 'Fork Dropouts', 2, 'EA', 0.50, 0.80, 0.20, 0.50, 2.0000, 4.00, 2.00, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'FORK-006', 'Brake Mount (Cantilever Posts)', 2, 'EA', 0.30, 0.50, 0.13, 0.20, 1.1300, 2.26, 1.13, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (1, 'DRV-001', 'Drivetrain Assembly', 1, 'EA', 0.00, 4.00, 1.00, 0.00, 5.0000, 86.75, 86.75, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-002', 'Crankset Assembly', 1, 'EA', 0.00, 2.00, 0.50, 0.00, 2.5000, 31.81, 31.81, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CRK-001', 'Right Crank Arm (w/ chainrings)', 1, 'EA', 3.00, 2.00, 0.50, 2.50, 8.0000, 8.00, 8.00, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CRK-002', 'Left Crank Arm', 1, 'EA', 2.50, 1.50, 0.38, 2.00, 6.3800, 6.38, 6.38, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CRK-003', 'Inner Chainring 24T', 1, 'EA', 1.50, 1.00, 0.25, 0.80, 3.5500, 3.55, 3.55, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CRK-004', 'Middle Chainring 34T', 1, 'EA', 1.80, 1.20, 0.30, 1.00, 4.3000, 4.30, 4.30, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CRK-005', 'Outer Chainring 42T', 1, 'EA', 2.00, 1.50, 0.38, 1.20, 5.0800, 5.08, 5.08, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CRK-006', 'Chainring Bolts', 5, 'EA', 0.15, 0.10, 0.03, 0.12, 0.4000, 2.00, 0.40, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-003', 'Bottom Bracket', 1, 'EA', 0.00, 1.50, 0.38, 0.00, 1.8800, 8.83, 8.83, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'BB-001', 'Bottom Bracket Cup LH', 1, 'EA', 0.40, 0.30, 0.08, 0.35, 1.1300, 1.13, 1.13, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'BB-002', 'Bottom Bracket Cup RH', 1, 'EA', 0.40, 0.30, 0.08, 0.35, 1.1300, 1.13, 1.13, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'BB-003', 'Bottom Bracket Spindle', 1, 'EA', 1.20, 0.80, 0.20, 0.80, 3.0000, 3.00, 3.00, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'BB-004', 'Bearing Retainer (LH)', 1, 'EA', 0.35, 0.15, 0.04, 0.10, 0.6400, 0.64, 0.64, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'BB-005', 'Bearing Retainer (RH)', 1, 'EA', 0.35, 0.15, 0.04, 0.10, 0.6400, 0.64, 0.64, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'BB-006', 'Lock Ring', 1, 'EA', 0.20, 0.10, 0.03, 0.08, 0.4100, 0.41, 0.41, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-004', 'Rear Cassette', 1, 'EA', 0.00, 1.00, 0.25, 0.00, 1.2500, 10.46, 10.46, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-001', 'Cog 14T', 1, 'EA', 0.40, 0.20, 0.05, 0.30, 0.9500, 0.95, 0.95, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-002', 'Cog 16T', 1, 'EA', 0.45, 0.22, 0.06, 0.32, 1.0500, 1.05, 1.05, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-003', 'Cog 18T', 1, 'EA', 0.50, 0.25, 0.06, 0.35, 1.1600, 1.16, 1.16, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-004', 'Cog 21T', 1, 'EA', 0.55, 0.28, 0.07, 0.38, 1.2800, 1.28, 1.28, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-005', 'Cog 24T', 1, 'EA', 0.60, 0.30, 0.08, 0.40, 1.3800, 1.38, 1.38, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-006', 'Cog 28T', 1, 'EA', 0.70, 0.35, 0.09, 0.45, 1.5900, 1.59, 1.59, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CST-007', 'Cog 34T', 1, 'EA', 0.80, 0.40, 0.10, 0.50, 1.8000, 1.80, 1.80, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-005', 'Front Derailleur', 1, 'EA', 3.00, 2.00, 0.50, 1.50, 7.0000, 7.00, 7.00, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-006', 'Rear Derailleur', 1, 'EA', 4.00, 2.50, 0.63, 2.00, 9.1300, 9.13, 9.13, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-007', 'Shifters (Pair)', 1, 'ST', 5.00, 2.00, 0.50, 0.80, 8.3000, 8.30, 8.30, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (2, 'DRV-008', 'Shift Cables (Pair)', 1, 'ST', 0.00, 0.50, 0.13, 0.00, 0.6300, 3.09, 3.09, 'ASSEMBLY');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CBL-001', 'Shift Inner Cable (Rear)', 1, 'EA', 0.30, 0.15, 0.04, 0.00, 0.4900, 0.49, 0.49, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CBL-002', 'Shift Inner Cable (Front)', 1, 'EA', 0.30, 0.15, 0.04, 0.00, 0.4900, 0.49, 0.49, 'LEAF');
INSERT INTO costing_bom (level, part_number, part_name, qty, uom, material_cost, labor_cost, overhead_cost, machining_cost, unit_cost, extended_cost, rolled_total, cost_type) VALUES (3, 'CBL-003', 'Shift Cable Housing', 2, 'EA', 0.25, 0.10, 0.03, 0.00, 0.3800, 0.76, 0.38, 'LEAF');
-- engineering_change_orders (10 rows from engineering-change-orders.csv)
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0001', 'Top Tube Material Upgrade for Weight Reduction', 'Replace Top Tube material from Al 6061-T6 to Al 7075-T6 to reduce frame weight by 120g while maintaining yield strength above 450 MPa. Requires updated weld procedure.', 'APPROVED', 'FRM-003', 'F', 'G', 3, 'MATERIAL_CHANGE', 'Aluminum alloy: 6061-T6 -> 7075-T6; Wall thickness: 1.2 mm -> 1.0 mm; Weight savings: 120 g', 3, 1, '2025-08-15', '2025-09-10', '2025-11-01', 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0002', 'Rear Dropouts Forged-to-CNC Conversion', 'Replace steel forged rear dropouts with CNC-machined 7075 aluminum dropouts to save 45g per dropout. Increased dimensional accuracy for better wheel alignment.', 'APPROVED', 'FRM-010', 'M', 'N', 2, 'MATERIAL_CHANGE', 'Process: forged steel -> CNC 7075 Al; Weight: 28g -> 12g each; Tolerance: ±0.3 mm -> ±0.05 mm', 2, 1, '2025-11-20', '2026-01-08', '2026-03-01', 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0003', 'Chain Upgrade to Corrosion-Resistant Variant', 'Replace KMC Z50 chain with KMC Z51 nickel-plated variant for improved corrosion resistance in wet-weather markets. Backward compatible with existing drivetrain.', 'REVIEW', 'DRV-009', 'H', 'I', 2, 'SUPPLIER_CHANGE', 'Model: KMC Z50 -> KMC Z51; Coating: unplated -> nickel-plated; Salt spray: 24 hr -> 72 hr; Cost increase: +$0.45/unit', 1, 5, '2026-02-10', NULL, NULL, 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0004', 'Add Puncture Protection to Front Inner Tube', 'Add Slime-brand puncture sealant inside front inner tube to reduce flat tire incidence by estimated 60%. Increases tubewall thickness by 0.3 mm.', 'DRAFT', 'WHL-007', 'L', 'M', 2, 'MATERIAL_CHANGE', 'Tube: standard butyl -> Slime-filled butyl; Wall: 1.0 mm -> 1.3 mm; Weight: 140 g -> 165 g; Target flat rate: 4.2% -> 1.7%', 1, NULL, '2026-03-22', NULL, NULL, 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0005', 'Front Brake Pad Compound Upgrade to Ceramic', 'Replace OEM rubber brake pads with ceramic compound pads for improved wet-weather braking performance and reduced rim wear. Increase pad service life by ~40%.', 'APPROVED', 'BRK-004', 'B', 'C', 2, 'MATERIAL_CHANGE', 'Pad compound: standard rubber -> ceramic-infused rubber; Wet braking coeff: 0.28 -> 0.38; Rim wear rate: 0.12mm/1000km -> 0.07mm/1000km', 4, 2, '2025-10-05', '2025-11-15', '2026-02-01', 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0006', 'Switch to Lock-On Ergonomic Grips', 'Replace standard slip-on rubber grips with lock-on ergonomic grips with aluminum clamp collars. Eliminates grip rotation under heavy use and improves rider comfort.', 'REVIEW', 'CPT-005', 'D', 'E', 2, 'DESIGN_CHANGE', 'Type: slip-on rubber -> lock-on ergonomic; Collar: none -> CNC Al 6061; OD: 30 mm -> 32 mm (tapered); Length: 130 mm -> 135 mm', 3, 1, '2026-01-14', NULL, NULL, 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0007', 'Pedal Upgrade from Nylon to Aluminum Platform', 'Replace nylon composite pedals with CNC aluminum platform pedals for increased durability and better grip. Include replaceable steel pins.', 'DRAFT', 'PED-001', 'Y', 'Z', 1, 'MATERIAL_CHANGE', 'Body: nylon composite -> Al 6061-T6 CNC; Pins: molded plastic -> M3 steel replaceable (8 per pedal); Bearing: loose ball -> sealed cartridge; Weight: 310g -> 380g', 5, NULL, '2026-04-05', NULL, NULL, 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0008', 'Steerer Tube Wall Thickness Increase for Safety Margin', 'Increase steerer tube wall thickness from 1.2 mm to 1.5 mm to address fatigue test failures at 200k cycles under 180 kg rider load. Reduce ID from 22.2 mm to 21.6 mm.', 'APPROVED', 'FORK-003', 'R', 'S', 2, 'DIMENSION_CHANGE', 'Wall thickness: 1.2 mm -> 1.5 mm; ID: 22.2 mm -> 21.6 mm; Fatigue life: 180k cycles -> 350k cycles; Weight increase: +18 g', 4, 2, '2025-06-20', '2025-08-01', '2025-10-15', 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0009', 'Seatpost Offset Head for Improved Saddle Adjustment', 'Add 20 mm offset head to seatpost to provide increased saddle fore-aft adjustment range. Compatible with existing 27.2 mm seat tube and saddle rail clamp.', 'REVIEW', 'SET-003', 'Z', 'AA', 2, 'DESIGN_CHANGE', 'Head: straight (0 mm offset) -> offset (20 mm set-back); Clamp: 2-bolt side clamp -> 2-bolt hidden; Weight: 285 g -> 315 g; Rail compatibility: 7 mm round -> 7 mm round/oval', 2, 4, '2025-12-01', NULL, NULL, 'RELEASED');
INSERT INTO engineering_change_orders (eco_number, eco_title, eco_description, eco_status, part_number, current_revision, new_revision, affected_bom_level, change_type, change_detail, change_drafter, change_approver, drafted_date, approved_date, implemented_date, new_status) VALUES ('ECO-0010', 'Cog 18T Surface Hardening for Extended Wear Life', 'Change 18T cassette cog from nickel-plated steel to induction-hardened chromoly steel to extend service life by 300% in high-torque gear position.', 'APPROVED', 'CST-003', 'F', 'G', 3, 'MATERIAL_CHANGE', 'Material: nickel-plated steel -> induction-hardened 4130 CrMo; Hardness: 35 HRC surface -> 58 HRC surface; Wear life: 8000 km -> 24000 km; Cost: +$0.18/unit', 1, 3, '2025-05-10', '2025-06-20', '2025-08-01', 'RELEASED');

-- approved_manufacturer_list (164 rows from aml.csv)
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'BicycleCo Manufacturing', 'BIKE-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 18.75, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('BRK-001', 'Y', 'Braking System Assembly', 'BicycleCo Manufacturing', 'BRK-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 3.75, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('CPT-001', 'N', 'Cockpit Assembly', 'BicycleCo Manufacturing', 'CPT-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 2.5, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('DRV-001', 'H', 'Drivetrain Assembly', 'BicycleCo Manufacturing', 'DRV-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 5.0, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('FORK-001', 'O', 'Fork Assembly', 'BicycleCo Manufacturing', 'FORK-001', 'PREFERRED', 'FABRICATED', 'Yes', 7, 6.25, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-20', 'In-house fork assembly.');
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('FRM-001', 'J', 'Frame Assembly', 'BicycleCo Manufacturing', 'FRM-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 10.0, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('HDW-001', 'Q', 'Hardware & Fasteners Kit', 'BicycleCo Manufacturing', 'HDW-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 0.63, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('PED-001', 'Y', 'Pedals (Pair)', 'BicycleCo Manufacturing', 'PED-001', 'PREFERRED', 'FABRICATED', 'Yes', 3, 1.25, 'USD', 'RoHS 3 Compliant', 'A', '2024-02-10', 'In-house production.');
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('SET-001', 'Y', 'Seat Assembly', 'BicycleCo Manufacturing', 'SET-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 1.88, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('WHL-001', 'J', 'Front Wheel Assembly', 'BicycleCo Manufacturing', 'WHL-001', 'PREFERRED', 'FABRICATED', 'Yes', 10, 7.5, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('WHL-009', 'U', 'Rear Wheel Assembly', 'BicycleCo Manufacturing', 'WHL-009', 'PREFERRED', 'FABRICATED', 'Yes', 10, 8.13, 'USD', 'RoHS 3 Compliant', 'A', '2024-01-01', NULL);
INSERT INTO approved_manufacturer_list (part_number, part_revision, part_name, manufacturer_name, manufacturer_part_number, manufacturer_status, source_type, preferred_flag, lead_time_days, unit_cost, currency, compliance_status, quality_rating, approval_date, notes) VALUES ('BRK-002', 'V', 'Brake Lever (Left)', 'Shimano Inc.', 'BL-EF41', 'PREFERRED', 'PURCHASED', 'Yes', 21, 5.38, 'USD', 'RoHS 3 Compliant', 'A', '2025-01-15', 'Primary supplier. Approved for production.');
-- approved_vendor_list (177 rows from avl.csv)
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-001', 'P', 'Hub Shell - Front', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-001', 'PREFERRED', 'Yes', 2, 2.03, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-002', 'T', 'Hub Axle - Front', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-002', 'PREFERRED', 'Yes', 2, 1.6, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-003', 'Q', 'Ball Bearings - Front Hub', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-003', 'PREFERRED', 'Yes', 2, 0.12, 'USD', 1, 'ST', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-004', 'P', 'Hub Cones - Front', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-004', 'PREFERRED', 'Yes', 2, 0.7, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-005', 'O', 'Hub Locknuts - Front', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-005', 'PREFERRED', 'Yes', 2, 0.4, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-006', 'E', 'Quick Release Skewer - Front', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-006', 'PREFERRED', 'Yes', 2, 1.08, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-007', 'B', 'Hub Shell - Rear', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-007', 'PREFERRED', 'Yes', 2, 2.35, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-008', 'U', 'Hub Axle - Rear', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-008', 'PREFERRED', 'Yes', 2, 1.81, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-009', 'P', 'Ball Bearings - Rear Hub', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-009', 'PREFERRED', 'Yes', 2, 0.15, 'USD', 1, 'ST', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-010', 'P', 'Hub Cones - Rear', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-010', 'PREFERRED', 'Yes', 2, 0.78, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-011', 'Q', 'Hub Locknuts - Rear', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-011', 'PREFERRED', 'Yes', 2, 0.47, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-012', 'X', 'Freewheel Body', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-012', 'PREFERRED', 'Yes', 2, 3.3, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('HUB-013', 'M', 'Quick Release Skewer - Rear', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'HUB-013', 'PREFERRED', 'Yes', 2, 1.24, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('SDL-001', 'K', 'Saddle Shell', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'SDL-001', 'PREFERRED', 'Yes', 2, 2.75, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('SDL-002', 'D', 'Saddle Padding', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'SDL-002', 'PREFERRED', 'Yes', 2, 0.88, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('SDL-003', 'N', 'Saddle Cover', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'SDL-003', 'PREFERRED', 'Yes', 2, 1.1, 'USD', 1, 'EA', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');
INSERT INTO approved_vendor_list (part_number, part_revision, part_name, vendor_name, vendor_site, vendor_contact, vendor_part_number, vendor_status, preferred_flag, lead_time_days, unit_price, currency, min_order_qty, moq_uom, payment_terms, shipping_method, contract_number, iso_certified, compliance_status, approval_date, notes) VALUES ('SDL-004', 'H', 'Saddle Rails (Pair)', 'BicycleCo Supply Chain', 'Portland, OR, USA', 'procurement@bicycleco.com', 'SDL-004', 'PREFERRED', 'Yes', 2, 2.53, 'USD', 1, 'PR', 'Net 30 (Intercompany)', 'Internal Transfer', 'INT-2024-001', 'Yes', 'RoHS 3 Compliant', '2024-01-01', 'Internal supply chain. Direct from manufacturing.');

-- cad_metadata (609 rows from cad-metadata.csv)
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'DRAFT', 'BIKE-001_RH.sldasm', 'SLDASM', 'SolidWorks 2024', '2024 SP4', 'AWS S3', 's3://bicycleco-cad-us-east-1/BIKE-001/BIKE-001_RH.sldasm', 9802360, 'C099FA23A6275E89', 1, '2013-03-22', '2013-08-11', 'DRW-BIKE-001-H', 'ASSEMBLY', 'FABRICATED', 'Cloud CAD vault. US East 1 region. Versioned bucket.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'DRAFT', 'BIKE-001_RH.sldasm', 'SLDASM', 'SolidWorks 2024', '2024 SP4', 'LocalServer', '\\cad-server-01\bicycleco\vault\BIKE-001\BIKE-001_RH.sldasm', 9802360, 'C099FA23A6275E89', 1, '2013-03-22', '2013-08-11', 'DRW-BIKE-001-H', 'ASSEMBLY', 'FABRICATED', 'On-premises Windows file server. Daily backup.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'DRAFT', 'BIKE-001_RH.sldasm', 'SLDASM', 'SolidWorks 2024', '2024 SP4', 'Git', 'https://git.bicycleco.com/plm/cad-models.git/tree/main/BIKE-001/BIKE-001_RH.sldasm', 9802360, 'C099FA23A6275E89', 1, '2013-03-22', '2013-08-11', 'DRW-BIKE-001-H', 'ASSEMBLY', 'FABRICATED', 'Git LFS tracked. Commit history available.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'DRAFT', 'BIKE-001_RH.stp', 'STEP', 'SolidWorks 2024', '2024 SP4', 'AWS S3', 's3://bicycleco-cad-us-east-1/BIKE-001/BIKE-001_RH.stp', 9802360, 'C099FA23A6275E89', 1, '2013-03-22', '2013-08-11', 'DRW-BIKE-001-H', 'ASSEMBLY', 'FABRICATED', 'Neutral STEP format for downstream consumption. Auto-generated from native CAD.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BIKE-001', 'H', 'Complete Bicycle - 21-Speed Hybrid', 'DRAFT', 'BIKE-001_RH.stp', 'STEP', 'SolidWorks 2024', '2024 SP4', 'Git', 'https://git.bicycleco.com/plm/cad-models.git/tree/main/BIKE-001/BIKE-001_RH.stp', 9802360, 'C099FA23A6275E89', 1, '2013-03-22', '2013-08-11', 'DRW-BIKE-001-H', 'ASSEMBLY', 'FABRICATED', 'STEP export. Auto-generated on commit hook.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BRK-001', 'Y', 'Braking System Assembly', 'RELEASED', 'BRK-001_RY.sldasm', 'SLDASM', 'SolidWorks 2024', '2024 SP4', 'AWS S3', 's3://bicycleco-cad-us-east-1/BRK-001/BRK-001_RY.sldasm', 1014523, 'AEE500131CEBE368', 2, '2020-05-23', '2024-08-30', 'DRW-BRK-001-Y', 'ASSEMBLY', 'FABRICATED', 'Cloud CAD vault. US East 1 region. Versioned bucket.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BRK-001', 'Y', 'Braking System Assembly', 'RELEASED', 'BRK-001_RY.sldasm', 'SLDASM', 'SolidWorks 2024', '2024 SP4', 'LocalServer', '\\cad-server-01\bicycleco\vault\BRK-001\BRK-001_RY.sldasm', 1014523, 'AEE500131CEBE368', 2, '2020-05-23', '2024-08-30', 'DRW-BRK-001-Y', 'ASSEMBLY', 'FABRICATED', 'On-premises Windows file server. Daily backup.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BRK-001', 'Y', 'Braking System Assembly', 'RELEASED', 'BRK-001_RY.sldasm', 'SLDASM', 'SolidWorks 2024', '2024 SP4', 'Git', 'https://git.bicycleco.com/plm/cad-models.git/tree/main/BRK-001/BRK-001_RY.sldasm', 1014523, 'AEE500131CEBE368', 2, '2020-05-23', '2024-08-30', 'DRW-BRK-001-Y', 'ASSEMBLY', 'FABRICATED', 'Git LFS tracked. Commit history available.');
INSERT INTO cad_metadata (part_number, part_revision, part_name, status, cad_file_name, cad_file_format, cad_system, cad_version, file_reference_type, file_reference_url, file_size_bytes, file_checksum, modeling_author, cad_created_date, cad_modified_date, drawing_number, model_type, source_type, notes) VALUES ('BRK-001', 'Y', 'Braking System Assembly', 'RELEASED', 'BRK-001_RY.stp', 'STEP', 'SolidWorks 2024', '2024 SP4', 'AWS S3', 's3://bicycleco-cad-us-east-1/BRK-001/BRK-001_RY.stp', 1014523, 'AEE500131CEBE368', 2, '2020-05-23', '2024-08-30', 'DRW-BRK-001-Y', 'ASSEMBLY', 'FABRICATED', 'Neutral STEP format for downstream consumption. Auto-generated from native CAD.');

PRAGMA foreign_keys = ON;


-- ============================================================
-- Default Roles Seed Data
-- ============================================================
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('reader', 'Standard user with read access', date('now'));
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('author', 'Can create and edit parts/ECOs', date('now'));
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('tenantadmin', 'Full administrative access for a tenant', date('now'));
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('quality', 'QA approval authority', date('now'));
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('manufacturing', 'Manufacturing approval authority', date('now'));
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('reviewer', 'Can review and comment on changes', date('now'));
INSERT OR IGNORE INTO roles (name, description, created_at) VALUES ('approver', 'Can approve/reject change requests', date('now'));

-- ============================================================
-- Default Workflow Templates Seed Data
-- ============================================================
-- Standard Part Release workflow template for tenant_id=1
INSERT OR IGNORE INTO workflow_templates (name, object_type, definition, is_active, tenant_id, created_at)
SELECT 'Standard Part Release', 'part',
'{"stages": [{"name": "Engineering", "parallel": false, "steps": [{"key": "eng", "name": "Engineering Review", "assignee_type": "role", "assignee": "author"}]}, {"name": "Approvals", "parallel": true, "steps": [{"key": "qa", "name": "QA Approval", "assignee_type": "role", "assignee": "quality"}, {"key": "mfg", "name": "Mfg Approval", "assignee_type": "role", "assignee": "manufacturing"}]}, {"name": "Release", "parallel": false, "steps": [{"key": "rel", "name": "Release", "assignee_type": "role", "assignee": "tenantadmin"}]}]}',
TRUE, 1, date('now')
WHERE NOT EXISTS (SELECT 1 FROM workflow_templates WHERE tenant_id=1 AND object_type='part');

-- Standard ECO Release workflow template for tenant_id=1
INSERT OR IGNORE INTO workflow_templates (name, object_type, definition, is_active, tenant_id, created_at)
SELECT 'Standard ECO Release', 'eco',
'{"stages": [{"name": "Review", "parallel": false, "steps": [{"key": "rev", "name": "Change Review", "assignee_type": "role", "assignee": "author"}]}, {"name": "Approvals", "parallel": true, "steps": [{"key": "qa", "name": "QA Approval", "assignee_type": "role", "assignee": "quality"}, {"key": "mfg", "name": "Mfg Approval", "assignee_type": "role", "assignee": "manufacturing"}]}, {"name": "Release", "parallel": false, "steps": [{"key": "rel", "name": "Release Change", "assignee_type": "role", "assignee": "tenantadmin"}]}]}',
TRUE, 1, date('now')
WHERE NOT EXISTS (SELECT 1 FROM workflow_templates WHERE tenant_id=1 AND object_type='eco');

-- ============================================================
-- Master Admin Seed Data
-- ============================================================
-- Note: The masteradmin user is created with password 'superadmin'
-- The password hash below is for 'superadmin' using bcrypt
INSERT OR IGNORE INTO users (username, full_name, email, password_hash, tenant_id, is_active, created_date, role)
SELECT 'masteradmin', 'Master Admin', NULL,
'$2b$12$/lprcRhuQOtubH2mNs/RTeEY8KHvNZozMOVDE1E77EPNPjbSs2lZy',
1, TRUE, date('now'), NULL
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='masteradmin');

-- ============================================================
-- Dummy users for each role across all tenants
-- ============================================================
-- Password for all: user1234 (bcrypt hash)
INSERT OR IGNORE INTO users (user_id, username, full_name, email, password_hash, tenant_id, role, is_active, created_date) VALUES
    -- Tenant 1: BicycleCo (adds tenantadmin + author)
    (6,  'bicycleadmin',  'Alice Walker',     'alice.walker@bicycleco.com',  '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, 'tenantadmin', TRUE, '2021-03-01'),
    (7,  'bicycleauthor', 'Bob Norris',       'bob.norris@bicycleco.com',    '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 1, 'author',      TRUE, '2021-04-01'),

    -- Tenant 2: CycleWorks
    (8,  'cycleadmin',    'Carol Stevens',    'carol.stevens@cycleworks.com',      '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 2, 'tenantadmin', TRUE, '2020-07-01'),
    (9,  'cycleauthor',   'Dan Ortiz',        'dan.ortiz@cycleworks.com',          '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 2, 'author',      TRUE, '2020-08-01'),
    (10, 'cycleuser',     'Eva Martens',      'eva.martens@cycleworks.com',        '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 2, 'reader',      TRUE, '2021-01-15'),

    -- Tenant 3: VeloParts
    (11, 'velopadmin',    'Frank Huang',      'frank.huang@veloparts.com',    '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 3, 'tenantadmin', TRUE, '2021-04-01'),
    (12, 'velopauthor',   'Grace Kim',        'grace.kim@veloparts.com',      '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 3, 'author',      TRUE, '2021-05-01'),
    (13, 'velopuser',     'Henry Liu',        'henry.liu@veloparts.com',      '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 3, 'reader',      TRUE, '2021-06-01'),

    -- Tenant 4: BikeTech Industries
    (14, 'bikeadmin',     'Iris Patel',       'iris.patel@biketech.com',      '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 4, 'tenantadmin', TRUE, '2022-02-01'),
    (15, 'bikeauthor',    'Jack Morrison',    'jack.morrison@biketech.com',   '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 4, 'author',      TRUE, '2022-03-01'),
    (16, 'bikeuser',      'Kara Lindholm',    'kara.lindholm@biketech.com',   '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 4, 'reader',      TRUE, '2022-04-01'),

    -- Tenant 5: PedalForce
    (17, 'pedaladmin',    'Liam Gallagher',   'liam.gallagher@pedalforce.com','$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 5, 'tenantadmin', TRUE, '2021-10-01'),
    (18, 'pedalauthor',   'Mia Rodriguez',    'mia.rodriguez@pedalforce.com', '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 5, 'author',      TRUE, '2021-11-01'),
    (19, 'pedaluser',     'Noah Bennett',     'noah.bennett@pedalforce.com',  '$2b$12$rc3Hp4Dy57vQaK24YyrQueVL2yRlPT1XUORS4z9brQXVtozw5q0Xe', 5, 'reader',      TRUE, '2022-01-01');

-- saved_queries (sample saved queries)
INSERT OR IGNORE INTO saved_queries (id, name, description, mode, definition, created_by, created_at, is_public, tenant_id) VALUES
    (1, 'All Released Parts', 'List all parts with RELEASED status', 'guided', '{"filters": [{"field": "status", "op": "=", "value": "RELEASED"}]}', 1, '2024-01-01', TRUE, 1),
    (2, 'High Cost Parts', 'Parts with unit cost > $100', 'sql', 'SELECT * FROM costing_bom WHERE unit_cost > 100', 1, '2024-01-02', FALSE, 1),
    (3, 'Recent ECOs', 'ECOs created in the last 30 days', 'guided', '{"filters": [{"field": "created_date", "op": ">=", "value": "last_30_days"}]}', 2, '2024-01-03', TRUE, 1);

-- app_settings (sample application settings)
INSERT OR IGNORE INTO app_settings (key, value) VALUES
    ('default_tenant_id', '1'),
    ('max_upload_size_mb', '10'),
    ('enable_elasticsearch', 'true'),
    ('llm_model', 'notset'),
    ('maintenance_mode', 'false');

-- workflow_templates (sample workflow templates)
INSERT OR IGNORE INTO workflow_templates (id, name, object_type, description, definition, is_active, created_by, tenant_id, created_at) VALUES
    (1, 'Standard Part Release', 'part', 'Standard workflow for releasing a new part', '{"stages": [{"name": "Draft Review", "steps": [{"name": "Review Design", "role": "author"}]}, {"name": "Approval", "steps": [{"name": "Approve Design", "role": "approver"}]}]}', TRUE, 1, 1, '2024-01-01'),
    (2, 'ECO Approval', 'eco', 'Workflow for approving engineering change orders', '{"stages": [{"name": "Technical Review", "steps": [{"name": "Review Change", "role": "author"}]}, {"name": "Final Approval", "steps": [{"name": "Approve ECO", "role": "approver"}]}]}', TRUE, 1, 1, '2024-01-01');

-- notifications (sample notifications)
INSERT OR IGNORE INTO notifications (id, user_id, type, title, message, link, is_read, created_at, tenant_id) VALUES
    (1, 1, 'workflow', 'Workflow Task Assigned', 'You have a new approval task for part FRM-001', '/workflow/tasks/1', FALSE, '2024-01-01', 1),
    (2, 2, 'eco', 'ECO Approved', 'ECO ECO-001 has been approved', '/eco/ECO-001', TRUE, '2024-01-02', 1),
    (3, 1, 'system', 'Welcome to PLM-IQ', 'Welcome to the PLM-IQ system!', '/dashboard', FALSE, '2024-01-01', 1);

-- favorites (sample favorites)
INSERT OR IGNORE INTO favorites (id, user_id, object_type, object_id, created_date, tenant_id) VALUES
    (1, 1, 'part', 'FRM-001', '2024-01-01', 1),
    (2, 1, 'part', 'BIKE-001', '2024-01-02', 1),
    (3, 2, 'document', '1', '2024-01-03', 1);

PRAGMA foreign_keys = ON;
